from .common import extract_telegram_channel_link
from .message_matcher_interface import IMessageMatcher
from .forwarded_messages_message_matcher import ForwardedMessagesMessageMatcher
from .text_url_channel_link_message_matcher import TextUrlChannelLinkMessageMatcher
from .url_channel_link_message_matcher import UrlChannelLinkMessageMatcher
